version: '3.8'

services:
  webapp:
    image: monum/recommender-system:v1
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=ecom
    volumes:
      - ./models:/app/models
      - ./static:/app/static
      - ./templates:/app/templates
    networks:
      - recommender-network

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecom
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - recommender-network

networks:
  recommender-network:
    driver: bridge

volumes:
  mysql-data: